### ISSUE TITLE
코틀린 추가 여부

### ISSUE THREAD

**Issue by YoungJun-L** [MangKyu/stream-quiz#9]
@MangKyu  님 안녕하세요!

여기 리포지토리 덕분에 스트림에 대해 많이 공부할 수 있었습니다. 감사합니다^^

혹시 kotlin 문법으로 여기 문제 약간 수정해서 만들어봤는데 public repo에 올려도 될까요?

현재 private 상태입니다

**Comment by MangKyu** [comment]
네네 올려도 괜찮습니다ㅎㅎ~
